### PR TITLE
Uses es6 import/exports

### PR DESCRIPTION
**Pull request by uniqname**
This PR changes the source file to an es6 module. It also identifies the source file as an the "main" file for tools that are es6 aware.

### CODE REVIEW

**Comment by kjbekkelund** [comment]
LGTM :+1: 

Maybe squash the commits?

**Comment by uniqname** [comment]
Commit squashing appears to be beyond my git-fu. Clearly I need to spend more time in the git dojo.

**Comment by kjbekkelund** [comment]
No problem, @uniqname :)

If you want to give it a go, you can try with:

```
git reset --soft HEAD~3
git commit -m "Use ES6 import/export"
```

(This will merge the three last commits)

Then force push to your branch:

```
git push -f
```

But no problem if you don't get it working.

**Comment by kjbekkelund** [comment]
Hi @uniqname, I see you fought the crazy git apis :/ I went ahead and copied the ES6 changes you had done into a new PR: #110.

Thanks for working on this!

**Pull request closed without merging**
