### PR TITLE
Experimental sync logic

### PR DESCRIPTION
**Pull request by jlongster**
@mariocasciaro @kadmil @box-turtle @amccloud Looping you in because you were involved in #12 and #30.

This is an experiment to simplify things even further. So far we've had trouble being compatible with HashHistory and also triggering multiple updates of the same URL when transitioning. This should fix all of that.

This is also fixes an issue where multiple calls to `updatePath` *should* trigger multiple route updates. Right now if you click the same `<Link>` multiple times it does trigger a route update each time, even though it's going to the same URL. Previous behavior would not do this, but with this PR it does.

Can everyone try out this PR and let me know of any obvious problems? I've tested it in simple cases so far.

### CODE REVIEW

**Comment by mariocasciaro** [comment]
I tried your experimental branch in my project, so far so good, it seems to be working fine.

**Comment by ZucchiniZe** [comment]
Just tried this branch and it looks like it is working

**Comment by ZucchiniZe** [comment]
Also, you probably want to change the main property in the package.json from `lib/index` to `src/index`

**Comment by amccloud** [comment]
@ZucchiniZe lib/index is correct. Since you installed from github you need to run `npm run build`

**Comment by ZucchiniZe** [comment]
Ah, that makes sense, thank you!

**Comment by amccloud** [comment]
@jlongster works for me :+1:

**Comment by jlongster** [comment]
Awesome! I think I'm going to land a simple test suite along with this so we can start adding tests over time as well. Still want to make sure this doesn't break anything.

**Comment by heydemo** [comment]
@amccloud thanks for the heads up - Using this branch and works perfectly

**Comment by n1k0** [comment]
Just confirming this patch makes the lib usable for me :)

**Comment by jlongster** [comment]
I just added some tests. Let's go ahead and land this and see how it goes.

**Comment by MrEfrem** [comment]
:+1:

**Pull request merged**
